const colors = {
  bordeaux: '#8a0c36',
  reddark: '#900',
  red: '#bd1118',
  pink: '#b31e61',
  rose: '#dc7095',
  orangedark: '#e96c0d',
  orange: '#e5ad02',
  yellow: '#fae500',
  yellowlight: '#ff0',
  sand: '#cec4a6',
  greendark: '#2f7820',
  green: '#029e5d',
  greenlight: '#93b923',
  lime: '#cbfe33',
  purpledark: '#51208c',
  bluenavy: '#1a237e',
  bluedark: '#1058c2',
  blue: '#31769b',
  bluelight: '#4fa8df',
  cyan: '#00b6d2',
  sea: '#84a8c4',
  black: '#000',
  graa1: '#3c3c3c',
  graa2: '#484848',
  graa3: '#999',
  graa4: '#c8c8c8',
  graa5: '#ddd',
  graa6: '#e5e5e5',
  graa7: '#efefef',
  white: '#fff',
  pastelred: '#db5040',
  pasteldarkred: '#954839',
  pastellightred: '#d67e9b',
  pastelgreen: '#9fc29c',
  pasteldarkgreen: '#91a34f',
  pastelyellow: '#d4c564',
};

const colorsNamed = {
  eb: colors.red,
  eb2: colors.reddark,
  breaking: colors.yellowlight,
  bruger: colors.bluelight,
  live: colors.black,
  native: colors.sand,
  native2: colors.sea,
  facebook: colors.blue,
  twitter: colors.bluelight,
  flash: colors.orange,
  forbrug: colors.cyan,
  leder: colors.bluenavy,
  livescore: colors.green,
  livescore2: colors.lime,
  nyheder: colors.bluedark,
  nyheder2: colors.black,
  sexsamliv: colors.pink,
  sexsamliv2: colors.rose,
  skolefodbold: colors.greenlight,
  sport: colors.green,
  tv: colors.red,
  underholdning: colors.purpledark,
};

const colorPairs = {
  bordeaux: { background: colors.bordeaux, color: colors.white },
  reddark: { background: colors.reddark, color: colors.white },
  red: { background: colors.red, color: colors.white },
  pink: { background: colors.pink, color: colors.white },
  rose: { background: colors.rose, color: colors.white },
  orangedark: { background: colors.orangedark, color: colors.white },
  orange: { background: colors.orange, color: colors.white },
  yellow: { background: colors.yellow, color: colors.white },
  yellowlight: { background: colors.yellowlight, color: colors.black },
  sand: { background: colors.sand, color: colors.white },
  greendark: { background: colors.greendark, color: colors.white },
  green: { background: colors.green, color: colors.white },
  greenlight: { background: colors.greenlight, color: colors.white },
  lime: { background: colors.lime, color: colors.black },
  purpledark: { background: colors.purpledark, color: colors.white },
  bluenavy: { background: colors.bluenavy, color: colors.white },
  bluedark: { background: colors.bluedark, color: colors.white },
  blue: { background: colors.blue, color: colors.white },
  bluelight: { background: colors.bluelight, color: colors.white },
  cyan: { background: colors.cyan, color: colors.white },
  sea: { background: colors.sea, color: colors.white },
  black: { background: colors.black, color: colors.white },
  graa1: { background: colors.graa1, color: colors.white },
  graa2: { background: colors.graa2, color: colors.white },
  graa3: { background: colors.graa3, color: colors.white },
  graa4: { background: colors.graa4, color: colors.black },
  graa5: { background: colors.graa5, color: colors.black },
  graa6: { background: colors.graa6, color: colors.black },
  graa7: { background: colors.graa7, color: colors.black },
  white: { background: colors.white, color: colors.black },
  pastelred: { background: colors.pastelred, color: colors.white },
  pasteldarkred: { background: colors.pasteldarkred, color: colors.white },
  pastellightred: { background: colors.pastellightred, color: colors.white },
  pastelgreen: { background: colors.pastelgreen, color: colors.white },
  pasteldarkgreen: { background: colors.pasteldarkgreen, color: colors.white },
  pastelyellow: { background: colors.pastelyellow, color: colors.white },
};

const colorPairsNamed = {
  eb: { background: colors.red, color: colors.white },
  eb2: { background: colors.reddark, color: colors.white },
  breaking: { background: colors.yellowlight, color: colors.black },
  bruger: { background: colors.bluelight, color: colors.white },
  live: { background: colors.black, color: colors.white },
  native: { background: colors.sand, color: colors.white },
  native2: { background: colors.sea, color: colors.white },
  facebook: { background: colors.blue, color: colors.white },
  twitter: { background: colors.bluelight, color: colors.white },
  flash: { background: colors.orange, color: colors.white },
  forbrug: { background: colors.cyan, color: colors.white },
  leder: { background: colors.bluenavy, color: colors.white },
  livescore: { background: colors.green, color: colors.white },
  livescore2: { background: colors.lime, color: colors.black },
  nyheder: { background: colors.bluedark, color: colors.white },
  nyheder2: { background: colors.black, color: colors.white },
  sexsamliv: { background: colors.pink, color: colors.white },
  sexsamliv2: { background: colors.rose, color: colors.white },
  skolefodbold: { background: colors.greenlight, color: colors.white },
  sport: { background: colors.green, color: colors.white },
  tv: { background: colors.red, color: colors.white },
  underholdning: { background: colors.purpledark, color: colors.white },
};

const borderColors = {
  black: colors.black,
  graa1: colors.graa1,
  graa2: colors.graa2,
  graa3: colors.graa3,
  graa4: colors.graa4,
  graa5: colors.graa5,
  graa6: colors.graa6,
  graa7: colors.graa7,
  white: colors.white,
};

module.exports = { borderColors, colors, colorsNamed, colorPairs, colorPairsNamed };
